// Generated by gencpp from file knu_ros_lecture/knuRosLecture.msg
// DO NOT EDIT!


#ifndef KNU_ROS_LECTURE_MESSAGE_KNUROSLECTURE_H
#define KNU_ROS_LECTURE_MESSAGE_KNUROSLECTURE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace knu_ros_lecture
{
template <class ContainerAllocator>
struct knuRosLecture_
{
  typedef knuRosLecture_<ContainerAllocator> Type;

  knuRosLecture_()
    : int32Data(0)
    , float32Data(0.0)
    , float64Data(0.0)
    , stringData()  {
    }
  knuRosLecture_(const ContainerAllocator& _alloc)
    : int32Data(0)
    , float32Data(0.0)
    , float64Data(0.0)
    , stringData(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _int32Data_type;
  _int32Data_type int32Data;

   typedef float _float32Data_type;
  _float32Data_type float32Data;

   typedef double _float64Data_type;
  _float64Data_type float64Data;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _stringData_type;
  _stringData_type stringData;




  typedef boost::shared_ptr< ::knu_ros_lecture::knuRosLecture_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::knu_ros_lecture::knuRosLecture_<ContainerAllocator> const> ConstPtr;

}; // struct knuRosLecture_

typedef ::knu_ros_lecture::knuRosLecture_<std::allocator<void> > knuRosLecture;

typedef boost::shared_ptr< ::knu_ros_lecture::knuRosLecture > knuRosLecturePtr;
typedef boost::shared_ptr< ::knu_ros_lecture::knuRosLecture const> knuRosLectureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::knu_ros_lecture::knuRosLecture_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::knu_ros_lecture::knuRosLecture_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace knu_ros_lecture

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'knu_ros_lecture': ['/home/turtle/catkin_ws/src/knu_ros_lecture/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::knu_ros_lecture::knuRosLecture_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::knu_ros_lecture::knuRosLecture_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knu_ros_lecture::knuRosLecture_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knu_ros_lecture::knuRosLecture_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knu_ros_lecture::knuRosLecture_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knu_ros_lecture::knuRosLecture_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::knu_ros_lecture::knuRosLecture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a47b7b41e31bbd789a10dc658a18ec37";
  }

  static const char* value(const ::knu_ros_lecture::knuRosLecture_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa47b7b41e31bbd78ULL;
  static const uint64_t static_value2 = 0x9a10dc658a18ec37ULL;
};

template<class ContainerAllocator>
struct DataType< ::knu_ros_lecture::knuRosLecture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "knu_ros_lecture/knuRosLecture";
  }

  static const char* value(const ::knu_ros_lecture::knuRosLecture_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::knu_ros_lecture::knuRosLecture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 int32Data\n\
float32 float32Data\n\
float64 float64Data\n\
string stringData\n\
";
  }

  static const char* value(const ::knu_ros_lecture::knuRosLecture_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::knu_ros_lecture::knuRosLecture_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.int32Data);
      stream.next(m.float32Data);
      stream.next(m.float64Data);
      stream.next(m.stringData);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct knuRosLecture_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::knu_ros_lecture::knuRosLecture_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::knu_ros_lecture::knuRosLecture_<ContainerAllocator>& v)
  {
    s << indent << "int32Data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.int32Data);
    s << indent << "float32Data: ";
    Printer<float>::stream(s, indent + "  ", v.float32Data);
    s << indent << "float64Data: ";
    Printer<double>::stream(s, indent + "  ", v.float64Data);
    s << indent << "stringData: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.stringData);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KNU_ROS_LECTURE_MESSAGE_KNUROSLECTURE_H
