// Generated by gencpp from file knu_ros_lecture/srvKnuRosLectureRequest.msg
// DO NOT EDIT!


#ifndef KNU_ROS_LECTURE_MESSAGE_SRVKNUROSLECTUREREQUEST_H
#define KNU_ROS_LECTURE_MESSAGE_SRVKNUROSLECTUREREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace knu_ros_lecture
{
template <class ContainerAllocator>
struct srvKnuRosLectureRequest_
{
  typedef srvKnuRosLectureRequest_<ContainerAllocator> Type;

  srvKnuRosLectureRequest_()
    : a(0)
    , b(0)  {
    }
  srvKnuRosLectureRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;




  typedef boost::shared_ptr< ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator> const> ConstPtr;

}; // struct srvKnuRosLectureRequest_

typedef ::knu_ros_lecture::srvKnuRosLectureRequest_<std::allocator<void> > srvKnuRosLectureRequest;

typedef boost::shared_ptr< ::knu_ros_lecture::srvKnuRosLectureRequest > srvKnuRosLectureRequestPtr;
typedef boost::shared_ptr< ::knu_ros_lecture::srvKnuRosLectureRequest const> srvKnuRosLectureRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace knu_ros_lecture

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'knu_ros_lecture': ['/home/turtle/catkin_ws/src/knu_ros_lecture/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "knu_ros_lecture/srvKnuRosLectureRequest";
  }

  static const char* value(const ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n\
int64 b\n\
";
  }

  static const char* value(const ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvKnuRosLectureRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::knu_ros_lecture::srvKnuRosLectureRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KNU_ROS_LECTURE_MESSAGE_SRVKNUROSLECTUREREQUEST_H
