// Generated by gencpp from file knu_ros_lecture/srvKnuRosLecture.msg
// DO NOT EDIT!


#ifndef KNU_ROS_LECTURE_MESSAGE_SRVKNUROSLECTURE_H
#define KNU_ROS_LECTURE_MESSAGE_SRVKNUROSLECTURE_H

#include <ros/service_traits.h>


#include <knu_ros_lecture/srvKnuRosLectureRequest.h>
#include <knu_ros_lecture/srvKnuRosLectureResponse.h>


namespace knu_ros_lecture
{

struct srvKnuRosLecture
{

typedef srvKnuRosLectureRequest Request;
typedef srvKnuRosLectureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvKnuRosLecture
} // namespace knu_ros_lecture


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::knu_ros_lecture::srvKnuRosLecture > {
  static const char* value()
  {
    return "d431cae597499d244ef1c576e21358c8";
  }

  static const char* value(const ::knu_ros_lecture::srvKnuRosLecture&) { return value(); }
};

template<>
struct DataType< ::knu_ros_lecture::srvKnuRosLecture > {
  static const char* value()
  {
    return "knu_ros_lecture/srvKnuRosLecture";
  }

  static const char* value(const ::knu_ros_lecture::srvKnuRosLecture&) { return value(); }
};


// service_traits::MD5Sum< ::knu_ros_lecture::srvKnuRosLectureRequest> should match 
// service_traits::MD5Sum< ::knu_ros_lecture::srvKnuRosLecture > 
template<>
struct MD5Sum< ::knu_ros_lecture::srvKnuRosLectureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::knu_ros_lecture::srvKnuRosLecture >::value();
  }
  static const char* value(const ::knu_ros_lecture::srvKnuRosLectureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::knu_ros_lecture::srvKnuRosLectureRequest> should match 
// service_traits::DataType< ::knu_ros_lecture::srvKnuRosLecture > 
template<>
struct DataType< ::knu_ros_lecture::srvKnuRosLectureRequest>
{
  static const char* value()
  {
    return DataType< ::knu_ros_lecture::srvKnuRosLecture >::value();
  }
  static const char* value(const ::knu_ros_lecture::srvKnuRosLectureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::knu_ros_lecture::srvKnuRosLectureResponse> should match 
// service_traits::MD5Sum< ::knu_ros_lecture::srvKnuRosLecture > 
template<>
struct MD5Sum< ::knu_ros_lecture::srvKnuRosLectureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::knu_ros_lecture::srvKnuRosLecture >::value();
  }
  static const char* value(const ::knu_ros_lecture::srvKnuRosLectureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::knu_ros_lecture::srvKnuRosLectureResponse> should match 
// service_traits::DataType< ::knu_ros_lecture::srvKnuRosLecture > 
template<>
struct DataType< ::knu_ros_lecture::srvKnuRosLectureResponse>
{
  static const char* value()
  {
    return DataType< ::knu_ros_lecture::srvKnuRosLecture >::value();
  }
  static const char* value(const ::knu_ros_lecture::srvKnuRosLectureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KNU_ROS_LECTURE_MESSAGE_SRVKNUROSLECTURE_H
