// Generated by gencpp from file knu_ros_lecture/srvKnuRosLectureResponse.msg
// DO NOT EDIT!


#ifndef KNU_ROS_LECTURE_MESSAGE_SRVKNUROSLECTURERESPONSE_H
#define KNU_ROS_LECTURE_MESSAGE_SRVKNUROSLECTURERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace knu_ros_lecture
{
template <class ContainerAllocator>
struct srvKnuRosLectureResponse_
{
  typedef srvKnuRosLectureResponse_<ContainerAllocator> Type;

  srvKnuRosLectureResponse_()
    : result(0)  {
    }
  srvKnuRosLectureResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int64_t _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srvKnuRosLectureResponse_

typedef ::knu_ros_lecture::srvKnuRosLectureResponse_<std::allocator<void> > srvKnuRosLectureResponse;

typedef boost::shared_ptr< ::knu_ros_lecture::srvKnuRosLectureResponse > srvKnuRosLectureResponsePtr;
typedef boost::shared_ptr< ::knu_ros_lecture::srvKnuRosLectureResponse const> srvKnuRosLectureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace knu_ros_lecture

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'knu_ros_lecture': ['/home/turtle/catkin_ws/src/knu_ros_lecture/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b05623554ab950ed237d43d45f0b4dd";
  }

  static const char* value(const ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b05623554ab950eULL;
  static const uint64_t static_value2 = 0xd237d43d45f0b4ddULL;
};

template<class ContainerAllocator>
struct DataType< ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "knu_ros_lecture/srvKnuRosLectureResponse";
  }

  static const char* value(const ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 result\n\
\n\
";
  }

  static const char* value(const ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvKnuRosLectureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::knu_ros_lecture::srvKnuRosLectureResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int64_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KNU_ROS_LECTURE_MESSAGE_SRVKNUROSLECTURERESPONSE_H
